### ISSUE TITLE
Explicit Stop, Pause, Resume and Destroy functionality

### ISSUE THREAD

**Issue by nishantcop** [tusharmath/Multi-threaded-downloader#38] opened 2015-04-27 09:36 UTC
STOP: Current download will be stopped and cleared
PAUSE: Should pause the current going download or downloadTask that is passed as  argument. 
RESUME: Should be able to resume specific download task by just providing ID or URL. 
DESTROY: handle cleaning up all threaded nicely if it's not done.

**Comment by tusharmath** [comment] 2016-02-01 13:05
Duplicate of #20

**Closed by tusharmath** 2016-02-01 13:05 UTC
Labels: duplicate
